name: Notify on Issues and PRs

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification for Issue
        if: github.event_name == 'issues'
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "🆕 New Issue Created",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🆕 New Issue Created"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Issue:*\n<${{ github.event.issue.html_url }}|#${{ github.event.issue.number }} ${{ github.event.issue.title }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author:*\n<${{ github.event.issue.user.html_url }}|${{ github.event.issue.user.login }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Labels:*\n${{ join(github.event.issue.labels.*.name, ', ') || 'None' }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Description:*\n${{ github.event.issue.body }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Issue"
                      },
                      "url": "${{ github.event.issue.html_url }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Send Slack Notification for Pull Request
        if: github.event_name == 'pull_request'
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "🔀 New Pull Request Created",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🔀 New Pull Request Created"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Pull Request:*\n<${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author:*\n<${{ github.event.pull_request.user.html_url }}|${{ github.event.pull_request.user.login }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n`${{ github.event.pull_request.head.ref }}` → `${{ github.event.pull_request.base.ref }}`"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Status:*\n${{ github.event.pull_request.draft && '📝 Draft' || '✅ Ready for Review' }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Labels:*\n${{ join(github.event.pull_request.labels.*.name, ', ') || 'None' }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Description:*\n${{ github.event.pull_request.body }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Pull Request"
                      },
                      "url": "${{ github.event.pull_request.html_url }}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Changes"
                      },
                      "url": "${{ github.event.pull_request.html_url }}/files"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
